name: CI PR and branches

# Controls when the action will run. Triggers the workflow on push on branch except main
# or pull request events but only for the main branch
on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare before build
        run: |
           sudo apt-get install -qy make curl patch
           uname -a
           docker-compose version
           docker version
           docker info

      - name: Build
        run: |
           set -e
           echo "# build and run"
           set -x
           ./tchap-build.sh

      - name: Run & test
        run: |
           set -e
           echo "# run and test"
           set -x
           ./tchap-bootstrap.sh

      - name: Clean
        run: |
           echo "# clean"
           ./tchap-clean.sh
