name: CI Merge main

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch
on:
  push:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: prepare before build
        run: |
           sudo apt-get install -qy make curl patch
           uname -a
           docker-compose version
           docker version
           docker info

      - name: Build
        run: |
           set -e
           echo "# build and run"
           set -x
           ./tchap-build.sh

      - name: Run & test
        run: |
           set -e
           echo "# run and test"
           set -x
           ./tchap-bootstrap.sh

      - name: Clean
        run: |
           echo "# clean"
           ./tchap-clean.sh
